import { diarizedTranscriptionResultSchema } from "./audio-domain.ts";
import { replayFindingSchema, type ReplayFinding } from "./evidence-replay.ts";

export const SAMPLE_REPLAY_TRANSCRIPTION = diarizedTranscriptionResultSchema.parse({
  text: "Thank you for calling Northstar Support. I have been charged twice and this is really frustrating. Before I review that, I need to verify the account. I can see why that would be upsetting, and I will stay with you while we fix it. I am reviewing the charges now. The extra charge should clear soon. Thanks for calling.",
  duration: 140,
  detectedLanguage: "English with Egyptian Arabic context",
  model: "sample-fixture-no-audio",
  createdAt: "2026-07-19T00:00:00.000Z",
  segments: [
    { id: "replay-001", speakerId: "speaker_0", role: "agent", start: 0, end: 12, text: "Thank you for calling Northstar Support. My name is Maya. How can I help?", originalText: "Thank you for calling Northstar Support. My name is Maya. How can I help?", editedText: null, isEdited: false },
    { id: "replay-002", speakerId: "speaker_1", role: "customer", start: 15, end: 30, text: "I have been charged twice and this is really frustrating. I need this fixed today.", originalText: "I have been charged twice and this is really frustrating. I need this fixed today.", editedText: null, isEdited: false },
    { id: "replay-003", speakerId: "speaker_0", role: "agent", start: 40, end: 55, text: "I found both charges. One looks temporary, so I will review it now.", originalText: "I found both charges. One looks temporary, so I will review it now.", editedText: null, isEdited: false },
    { id: "replay-004", speakerId: "speaker_0", role: "agent", start: 58, end: 72, text: "I can see why a duplicate charge would be upsetting. I will stay with you while we fix it.", originalText: "I can see why a duplicate charge would be upsetting. I will stay with you while we fix it.", editedText: null, isEdited: false },
    { id: "replay-005", speakerId: "speaker_0", role: "agent", start: 88, end: 102, text: "I am reviewing the charges now. Thank you for waiting.", originalText: "I am reviewing the charges now. Thank you for waiting.", editedText: null, isEdited: false },
    { id: "replay-006", speakerId: "speaker_0", role: "agent", start: 126, end: 140, text: "The extra charge should clear soon. Thanks for calling.", originalText: "The extra charge should clear soon. Thanks for calling.", editedText: null, isEdited: false },
  ],
});

export const SAMPLE_REPLAY_FINDINGS: ReplayFinding[] = replayFindingSchema.array().parse([
  { id: "event-greeting", segmentId: "replay-001", timestamp: 0, positionLabel: null, eventType: "milestone", title: "Greeting", speaker: "agent", quote: "Thank you for calling Northstar Support.", explanation: "The agent opens with a clear company greeting and introduces the purpose of the call.", category: "Greeting", suggestedResponse: null, coachingRecommendation: "Keep the greeting concise and pair it with the agent name and an offer to help.", improvedResponse: "Thank you for calling Northstar Support. My name is Maya. How can I help today?" },
  { id: "event-frustration", segmentId: "replay-002", timestamp: 18, positionLabel: null, eventType: "finding", title: "Customer frustration detected", speaker: "customer", quote: "this is really frustrating", explanation: "The customer states the emotional impact directly, creating an early opportunity to acknowledge the concern.", category: "Customer sentiment", suggestedResponse: "I can hear how frustrating this has been, and I will review both charges with you now.", coachingRecommendation: "Acknowledge the emotion before moving into investigation questions.", improvedResponse: "I can hear how frustrating this has been. Let me review both charges with you now." },
  { id: "event-verification", segmentId: "replay-003", timestamp: 44, positionLabel: null, eventType: "warning", title: "Verification missed", speaker: "agent", quote: "I found both charges.", explanation: "The agent begins discussing account details without a verified identity step in the sample transcript.", category: "Compliance", suggestedResponse: "Before I discuss the charges, may I verify the last four digits of the phone number on the account?", coachingRecommendation: "Complete the approved verification step before exposing account-specific information.", improvedResponse: "Before I discuss the charges, may I verify the last four digits of the phone number on the account?" },
  { id: "event-empathy", segmentId: "replay-004", timestamp: 62, positionLabel: null, eventType: "milestone", title: "Empathy and ownership", speaker: "agent", quote: "I can see why a duplicate charge would be upsetting.", explanation: "The response validates the customer’s experience and adds ownership without overpromising.", category: "Empathy", suggestedResponse: null, coachingRecommendation: "Retain this phrasing and follow it with a specific next action.", improvedResponse: "I can see why a duplicate charge would be upsetting. I will check both transactions and explain the next step." },
  { id: "event-dead-air", segmentId: "replay-005", timestamp: 91, positionLabel: null, eventType: "warning", title: "Possible dead air", speaker: "agent", quote: "I am reviewing the charges now.", explanation: "The timeline contains a long gap before this update. Without playable sample audio, it is flagged only as a possible silence interval.", category: "Call control", suggestedResponse: "I am still reviewing the second charge. This will take about another minute.", coachingRecommendation: "Give short progress updates during extended research to preserve confidence.", improvedResponse: "I am still reviewing the second charge. This will take about another minute—thank you for waiting." },
  { id: "event-closing", segmentId: "replay-006", timestamp: 130, positionLabel: null, eventType: "coaching", title: "Weak closing", speaker: "agent", quote: "Thanks for calling.", explanation: "The closing does not confirm the exact timeframe, escalation path, or whether the customer needs anything else.", category: "Closing", suggestedResponse: "The pending charge should clear within three business days. If it remains, reply to my confirmation email and we will review it immediately. Is there anything else I can help with?", coachingRecommendation: "Close with a timeframe, contingency, ownership path, and final offer of help.", improvedResponse: "The pending charge should clear within three business days. If it remains, reply to my email and we will review it immediately. Is there anything else I can help with?" },
]);
